// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJiyUoawFKNsiHhKcniC67vXfDOrEbUb8',
    appId: '1:66428657008:web:7028e9cb758eaa5faac3b5',
    messagingSenderId: '66428657008',
    projectId: 'gpa-calculator-app-c5252',
    authDomain: 'gpa-calculator-app-c5252.firebaseapp.com',
    storageBucket: 'gpa-calculator-app-c5252.firebasestorage.app',
    measurementId: 'G-97D7QR120S',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJiyUoawFKNsiHhKcniC67vXfDOrEbUb8',
    appId: '1:66428657008:web:1f8e2c636491b58eaac3b5',
    messagingSenderId: '66428657008',
    projectId: 'gpa-calculator-app-c5252',
    authDomain: 'gpa-calculator-app-c5252.firebaseapp.com',
    storageBucket: 'gpa-calculator-app-c5252.firebasestorage.app',
    measurementId: 'G-7BGHT3Y2KQ',
  );

}